name: Codestyle checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.1.3
        with:
          php-version: '7.3'
          tools: cs2pr, phpcpd, phpcs, phpmd

      - name: PHP copy past detector
        run: phpcpd src/

      - name: PHP code style
        run: phpcs src/

      - name: PHP mess detector
        run: phpmd src/ text ruleset.xml